# Generated by Django 4.1.6 on 2023-02-22 06:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0002_project_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="photo",
        ),
        migrations.AlterField(
            model_name="project",
            name="created_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
