# Generated by Django 4.1.6 on 2023-03-01 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0003_remove_project_photo_alter_project_created_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="photo",
            field=models.ImageField(
                blank=True, default="tree.png", null=True, upload_to=""
            ),
        ),
    ]
