# Generated by Django 4.1.6 on 2023-03-14 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0004_project_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to="photo/"),
        ),
    ]
