# Generated by Django 4.1.6 on 2023-03-16 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0005_alter_project_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="photo",
            field=models.ImageField(
                blank=True, default="fah.jpg", null=True, upload_to=""
            ),
        ),
    ]
