# Generated by Django 4.1.6 on 2023-03-16 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0006_alter_project_photo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="review",
            name="project",
        ),
        migrations.AddField(
            model_name="project",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="projects.review",
            ),
        ),
    ]
