# Generated by Django 4.1.6 on 2023-03-16 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0007_remove_review_project_project_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="review",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
    ]
