# Generated by Django 4.1.6 on 2023-03-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("projects", "0009_review_project_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="project",
            name="review",
        ),
        migrations.AddField(
            model_name="project",
            name="review",
            field=models.ManyToManyField(to="projects.review"),
        ),
    ]
